### ISSUE TITLE
Bug: Typo in allocating arrays in /src/laplace/rfmm2d.f

### ISSUE THREAD

**Issue by jimvicjor** [flatironinstitute/fmm2d#7]
When trying to use the rfmm2d_t_c_g subroutine, I noticed that the program crashed when the number of target points is larger than the number of sources. This is due to a typo in routine rfmm2d. When arrays are allocated for targets, ns is used instead of nt and therefore, it is not possible to have more targets than sources (this happens in lines 116, 123, 126 and 127 of rfmm2d.f (in /src/laplace/rfmm2d.f)). ns must be changed to nt in those lines.. . It then works fine. 
Same issue seems to be present in lfmm2d.f.
Hope you can fix it. 
Sorry if this is not the right channel/way to tell you. I'm an astrophysicist and not very used to github
Cheers,
Jorge

**Comment by askhamwhat** [comment]
Thank you, Jorge. This is exactly the right way to report something like this.
